#!/bin/bash -e

docker-compose exec client \
               ansible all \
               -m ping \
               -u vagrant \
               --key-file=.vagrant/machines/default/virtualbox/private_key
