#!/bin/bash -e

if [[ ! -e namespace ]]; then
    docker-compose exec client openssl rand -hex 6 | tr -d '\r\n' >namespace
fi
namespace=$(cat namespace)

docker-compose exec client \
               conjur policy load \
               --as-group=security_admin \
               --namespace=$namespace \
               /mnt/ansible-demo-policy.yml \
    | tee roles.json

docker-compose exec client bash -c 'grep user:alice /mnt/roles.json | jq -r .[]' >alice_api_key

echo 'View the loaded policy in the Conjur Enterprise UI:'
echo "https://localhost:8443/ui/policies/$namespace%2Fansible-demo"
