#!/bin/bash -e

namespace=$(cat namespace)

docker-compose exec client \
               env CONJUR_MAJOR_VERSION=4 \
               summon -D NAMESPACE=$namespace \
               bash -c 'ssh -i $SSH_PRIVATE_KEY_FILE -p 2222 vagrant@docker.for.mac.localhost'
