FROM cyberark/conjur-cli:4

RUN apt-get update && apt-get install -qy python3 python3-pip

RUN mkdir -p /ansible
WORKDIR /ansible
COPY ansible-requirements.txt .

RUN pip3 install --upgrade pip && pip3 install -r ansible-requirements.txt

CMD [ "sleep", "infinity" ]